(function(){var PHONE=window.PHONE=function(config){var defaultmedia={media:{audio:{},video:{facingMode:"user"}}};var config=merge(defaultmedia,config||{});var PHONE=function(){};var pubnub=PUBNUB(config);var pubkey=config.publish_key||'demo';var snapper=function(){return ' '}
var subkey=config.subscribe_key||'demo';var autocam=config.autocam!==false;var sessionid=PUBNUB.uuid();var mystream=null;var myvideo=document.createElement('video');var myconnection=false;var mediaconf=config.media;var conversations={};var PeerConnection=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection;var IceCandidate=window.mozRTCIceCandidate||window.RTCIceCandidate;var SessionDescription=window.RTCSessionDescription||window.mozRTCSessionDescription||window.webkitRTCSessionDescription;navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;var rtcconfig={iceServers:[{"urls":navigator.mozGetUserMedia?"stun:stun.services.mozilla.com":navigator.webkitGetUserMedia?"stun:stun.l.google.com:19302":"stun:23.21.150.121"},{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun1.l.google.com:19302"},{urls:"stun:stun2.l.google.com:19302"},{urls:"stun:stun3.l.google.com:19302"},{urls:"stun:stun4.l.google.com:19302"},{urls:"stun:23.21.150.121"},{urls:"stun:stun01.sipphone.com"},{urls:"stun:stun.ekiga.net"},{urls:"stun:stun.fwdnet.net"},{urls:"stun:stun.ideasip.com"},{urls:"stun:stun.iptel.org"},{urls:"stun:stun.rixtelecom.se"},{urls:"stun:stun.schlund.de"},{urls:"stun:stunserver.org"},{urls:"stun:stun.softjoys.com"},{urls:"stun:stun.voiparound.com"},{urls:"stun:stun.voipbuster.com"},{urls:"stun:stun.voipstunt.com"},{urls:"stun:stun.voxgratia.org"},{urls:"stun:stun.xten.com"}]};function add_servers(servers){if(servers.constructor===Array)
[].unshift.apply(rtcconfig.iceServers,servers);else rtcconfig.iceServers.unshift(servers);}
if('servers'in config)add_servers(config.servers);var messagecb=function(){};var readycb=function(){};var unablecb=function(){};var debugcb=function(){};var connectcb=function(){};var disconnectcb=function(){};var reconnectcb=function(){};var callstatuscb=function(){};var receivercb=function(){};PHONE.message=function(cb){messagecb=cb};PHONE.ready=function(cb){readycb=cb};PHONE.unable=function(cb){unablecb=cb};PHONE.callstatus=function(cb){callstatuscb=cb};PHONE.debug=function(cb){debugcb=cb};PHONE.connect=function(cb){connectcb=cb};PHONE.disconnect=function(cb){disconnectcb=cb};PHONE.reconnect=function(cb){reconnectcb=cb};PHONE.receive=function(cb){receivercb=cb};function get_conversation(number){var talk=conversations[number]||(function(number){var talk={number:number,status:'',image:document.createElement('img'),started:+new Date,imgset:false,imgsent:0,pc:new PeerConnection(rtcconfig),closed:false,usermsg:function(){},thumb:null,connect:function(){},end:function(){}};talk.pc.onaddstream=config.onaddstream||function(event){onaddstream(number,event)};;talk.pc.onicecandidate=function(event){onicecandidate(number,event)};talk.pc.number=number;talk.hangup=function(signal){if(talk.closed)return;talk.closed=true;talk.imgset=false;clearInterval(talk.snapi);if(signal!==false)transmit(number,{hangup:true});talk.end(talk);talk.pc.close();close_conversation(number);};talk.stop=function(){if(mystream)mystream.stop();return mystream;};talk.send=function(message){transmit(number,{usermsg:message});};talk.snap=function(){var pic=snapper();if(talk.closed)clearInterval(talk.snapi);transmit(number,{thumbnail:pic});var img=document.createElement('img');img.src=pic;return{data:pic,image:img};};talk.snapi=setInterval(function(){if(talk.imgsent++>1)return clearInterval(talk.snapi);talk.snap();},1500);talk.snap();talk.thumbnail=function(cb){talk.thumb=cb;return talk};talk.ended=function(cb){talk.end=cb;return talk};talk.connected=function(cb){talk.connect=cb;return talk};talk.message=function(cb){talk.usermsg=cb;return talk};if(mystream)talk.pc.addStream(mystream);update_conversation(talk,'connecting');conversations[number]=talk;return talk;})(number);return talk;}
function close_conversation(number){conversations[number]=null;delete conversations[number];}
function update_conversation(talk,status){talk.status=status;callstatuscb(talk);return talk;}
PHONE.number=function(){return config.number;};PHONE.history=function(settings){pubnub.history({channel:settings[number],callback:function(call_history){settings['history'](call_history[0]);}})};PHONE.dial=function(number,servers){if(!!servers)add_servers(servers);var talk=get_conversation(number);var pc=talk.pc;if(talk.dialed)return false;talk.dialed=true;pc.createOffer(function(offer){transmit(number,{hangup:true});transmit(number,offer,2);pc.setLocalDescription(offer,debugcb,debugcb);},debugcb);return talk;};PHONE.snap=function(message,number){if(number)return get_conversation(number).snap(message);var pic={};PUBNUB.each(conversations,function(number,talk){pic=talk.snap();});return pic;};PHONE.send=function(message,number){if(number)return get_conversation(number).send(message);PUBNUB.each(conversations,function(number,talk){talk.send(message);});};PHONE.hangup=function(number){if(number)return get_conversation(number).hangup();PUBNUB.each(conversations,function(number,talk){talk.hangup();});};PUBNUB.bind('unload,beforeunload',window,function(){if(PHONE.goodbye)return true;PHONE.goodbye=true;PUBNUB.each(conversations,function(number,talk){var mynumber=config.number;var packet={hangup:true};var message={packet:packet,id:sessionid,number:mynumber};var client=new XMLHttpRequest();var url='https://pubsub.pubnub.com/publish/'
+pubkey+'/'
+subkey+'/0/'
+number+'/0/'
+JSON.stringify(message);client.open('GET',url,false);client.send();talk.hangup();});return true;});function snapshots_setup(stream){var video=myvideo;var canvas=document.createElement('canvas');var context=canvas.getContext("2d");var snap={width:240,height:180};video.width=snap.width;video.height=snap.height;video.srcObject=stream;video.volume=0.0;video.play();canvas.width=snap.width;canvas.height=snap.height;snapper=function(){try{context.drawImage(video,0,0,snap.width,snap.height);}catch(e){}
return canvas.toDataURL('image/jpeg',0.30);};PHONE.video=video;}
function onaddstream(number,obj){var vid=document.createElement('video');var stream=obj.stream;var talk=get_conversation(number);vid.setAttribute('autoplay','autoplay');vid.setAttribute('playsinline','playsinline');vid.srcObject=stream;talk.video=vid;talk.connect(talk);}
function onicecandidate(number,event){if(!event.candidate)return;transmit(number,event.candidate);};function subscribe(){pubnub.subscribe({restore:true,channel:''+config.number,message:receive,disconnect:disconnectcb,reconnect:reconnectcb,connect:function(){onready(true)}});}
function onready(subscribed){if(subscribed)myconnection=true;if(myconnection&&autocam)readycb();if(!(mystream&&myconnection))return;connectcb();if(!autocam)readycb();}
function startcamera(){navigator.mediaDevices.getUserMedia(mediaconf).then(function(stream){if(!stream)return unablecb(stream);mystream=stream;snapshots_setup(stream);if(autocam)startsubscribe();},function(info){debugcb(info);return unablecb(info);});}
function startsubscribe(){onready();subscribe();}
function transmit(phone,packet,times,time){if(!packet)return;var number=''+config.number;var message={packet:packet,id:sessionid,number:number};debugcb(message);pubnub.publish({channel:phone,message:message});if(!times)return;time=time||1;if(time++>=times)return;setTimeout(function(){transmit(phone,packet,times,time);},150);}
function receive(message){debugcb(message);var talk=get_conversation(message.number);if(talk.closed)return;if(message.packet.usermsg){messagecb(talk,message.packet.usermsg);return talk.usermsg(talk,message.packet.usermsg);}
if(message.packet.thumbnail)return create_thumbnail(message);if(message.packet.hangup)return talk.hangup(false);if(message.packet.sdp&&!talk.received){talk.received=true;receivercb(talk);}
if(message.packet.sdp)add_sdp_offer(message);else add_ice_route(message);}
function create_thumbnail(message){var talk=get_conversation(message.number);talk.image.src=message.packet.thumbnail;if(!talk.thumb)return;if(!talk.imgset)talk.thumb(talk);talk.imgset=true;}
function add_sdp_offer(message){var talk=get_conversation(message.number);var pc=talk.pc;var type=message.packet.type=='offer'?'offer':'answer';if(type in talk)return;talk[type]=true;talk.dialed=true;update_conversation(talk,'routing');pc.setRemoteDescription(new SessionDescription(message.packet),function(){update_conversation(talk,'connected');if(pc.remoteDescription.type!='offer')return;pc.createAnswer(function(answer){pc.setLocalDescription(answer,debugcb,debugcb);transmit(message.number,answer,2);},debugcb);},debugcb);}
function add_ice_route(message){if(!message.packet)return;if(!message.packet.candidate)return;var talk=get_conversation(message.number);var pc=talk.pc;pc.addIceCandidate(new IceCandidate(message.packet),debugcb,debugcb);}
function merge(target,add){function isObject(obj){if(typeof obj=="object"){for(var key in obj){if(obj.hasOwnProperty(key)){return true;}}}
return false;}
for(var key in add){if(add.hasOwnProperty(key)){if(target[key]&&isObject(target[key])&&isObject(add[key])){merge(target[key],add[key]);}else{target[key]=add[key];}}}
return target;};PHONE.startcamera=startcamera;if(autocam)startcamera();else startsubscribe();return PHONE;};})();